note:
    pattern:  /
    defaults: { _controller: "VamsiSelfNoteBundle:Note:index" }

note_show:
    pattern:  /{id}/show
    defaults: { _controller: "VamsiSelfNoteBundle:Note:show" }

note_new:
    pattern:  /new
    defaults: { _controller: "VamsiSelfNoteBundle:Note:new" }

note_create:
    pattern:  /create
    defaults: { _controller: "VamsiSelfNoteBundle:Note:create" }
    requirements: { _method: post }

note_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "VamsiSelfNoteBundle:Note:edit" }

note_update:
    pattern:  /{id}/update
    defaults: { _controller: "VamsiSelfNoteBundle:Note:update" }
    requirements: { _method: post|put }

note_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "VamsiSelfNoteBundle:Note:delete" }
    requirements: { _method: post|delete }
