parameters:
#    vamsi_self_note.example.class: Vamsi\SelfNoteBundle\Example

services:
#    vamsi_self_note.example:
#        class: %vamsi_self_note.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
